version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

mkdocs:
  configuration: docs/docs/readdocs/mkdocs.yml
  docs_dir: docs/docs/readdocs

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: docs/docs/readdocs/requirements.txt
