version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
    
formats:
<<<<<<< HEAD
=======

>>>>>>> f8b5409aba839dfb1707e9d96cca8b9901308af6
  - pdf

mkdocs:
  configuration: docs/readdocs/mkdocs.yml
  fail_on_warning: false

python:
   install:
   - requirements: docs/readdocs/requirements.txt
