site_name: Security Home Mail Hub

site_url: https://claudiacoord.github.io/SecurityHomeMailHub/

docs_dir: docs/docs/readdocs

nav:

    - Home: docindex.md

    - About: docabout.md

theme:
# bootstrap386

  name: material

  palette:

    primary: pink

  features:

    - navigation.tabs

    - navigation.sections

copyright: Copyright &copy; 2018 - 2022 CC

markdown_extensions:

  - pymdownx.highlight

  - pymdownx.superfences

