//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeMailHub.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomeMailHub.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Add.
        /// </summary>
        internal static string BTN_ADD {
            get {
                return ResourceManager.GetString("BTN_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Attach.
        /// </summary>
        internal static string BTN_ATTACH {
            get {
                return ResourceManager.GetString("BTN_ATTACH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Check.
        /// </summary>
        internal static string BTN_CHECK {
            get {
                return ResourceManager.GetString("BTN_CHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check _All.
        /// </summary>
        internal static string BTN_CHECKALL {
            get {
                return ResourceManager.GetString("BTN_CHECKALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Clear.
        /// </summary>
        internal static string BTN_CLEAR {
            get {
                return ResourceManager.GetString("BTN_CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Close.
        /// </summary>
        internal static string BTN_CLOSE {
            get {
                return ResourceManager.GetString("BTN_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Delete.
        /// </summary>
        internal static string BTN_DELETE {
            get {
                return ResourceManager.GetString("BTN_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Export.
        /// </summary>
        internal static string BTN_EXPORT {
            get {
                return ResourceManager.GetString("BTN_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Import.
        /// </summary>
        internal static string BTN_IMPORT {
            get {
                return ResourceManager.GetString("BTN_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Open.
        /// </summary>
        internal static string BTN_OPEN {
            get {
                return ResourceManager.GetString("BTN_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Paste.
        /// </summary>
        internal static string BTN_PASTE {
            get {
                return ResourceManager.GetString("BTN_PASTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Reload.
        /// </summary>
        internal static string BTN_RELOAD {
            get {
                return ResourceManager.GetString("BTN_RELOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Reply.
        /// </summary>
        internal static string BTN_REPLAY {
            get {
                return ResourceManager.GetString("BTN_REPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Save.
        /// </summary>
        internal static string BTN_SAVE {
            get {
                return ResourceManager.GetString("BTN_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Send.
        /// </summary>
        internal static string BTN_SEND {
            get {
                return ResourceManager.GetString("BTN_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Sort.
        /// </summary>
        internal static string BTN_SORT {
            get {
                return ResourceManager.GetString("BTN_SORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Start.
        /// </summary>
        internal static string BTN_START {
            get {
                return ResourceManager.GetString("BTN_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Stop.
        /// </summary>
        internal static string BTN_STOP {
            get {
                return ResourceManager.GetString("BTN_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check incoming From address, anti-SPAM filter.
        /// </summary>
        internal static string CHKBOX_CHECKFROM {
            get {
                return ResourceManager.GetString("CHKBOX_CHECKFROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delivery local incoming message (not disabled this!).
        /// </summary>
        internal static string CHKBOX_DELIVERYLOC {
            get {
                return ResourceManager.GetString("CHKBOX_DELIVERYLOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Modify message delivered local, anti-spy.
        /// </summary>
        internal static string CHKBOX_DELIVERYMSGMOD {
            get {
                return ResourceManager.GetString("CHKBOX_DELIVERYMSGMOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not expire.
        /// </summary>
        internal static string CHKBOX_EXPIRE {
            get {
                return ResourceManager.GetString("CHKBOX_EXPIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Always flush messages when received (IMAP).
        /// </summary>
        internal static string CHKBOX_IMAPPURGE {
            get {
                return ResourceManager.GetString("CHKBOX_IMAPPURGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Always new message Id, anti-spy.
        /// </summary>
        internal static string CHKBOX_NEWMSGID {
            get {
                return ResourceManager.GetString("CHKBOX_NEWMSGID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New message send Immediately.
        /// </summary>
        internal static string CHKBOX_NEWMSGIMD {
            get {
                return ResourceManager.GetString("CHKBOX_NEWMSGIMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No warnings.
        /// </summary>
        internal static string CHKBOX_NOWARN {
            get {
                return ResourceManager.GetString("CHKBOX_NOWARN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete all messages.
        /// </summary>
        internal static string CHKBOX_POP3DELALL {
            get {
                return ResourceManager.GetString("CHKBOX_POP3DELALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PGP decrypt.
        /// </summary>
        internal static string CHKBOX_POP3PGP {
            get {
                return ResourceManager.GetString("CHKBOX_POP3PGP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Receive external mail only when sending messages.
        /// </summary>
        internal static string CHKBOX_RECEIVEONSEND {
            get {
                return ResourceManager.GetString("CHKBOX_RECEIVEONSEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save Attachments.
        /// </summary>
        internal static string CHKBOX_SAVEATTACH {
            get {
                return ResourceManager.GetString("CHKBOX_SAVEATTACH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Write session log.
        /// </summary>
        internal static string CHKBOX_SESSIONLOG {
            get {
                return ResourceManager.GetString("CHKBOX_SESSIONLOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Allow others to open this socket on the specified port.
        /// </summary>
        internal static string CHKBOX_SHARINGSOCKET {
            get {
                return ResourceManager.GetString("CHKBOX_SHARINGSOCKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Always add fake IP address to headers (SMTP).
        /// </summary>
        internal static string CHKBOX_SMTPFAKEIP {
            get {
                return ResourceManager.GetString("CHKBOX_SMTPFAKEIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Encrypt PGP email text if available.
        /// </summary>
        internal static string CHKBOX_SMTPPGPCRYPT {
            get {
                return ResourceManager.GetString("CHKBOX_SMTPPGPCRYPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Certify PGP email signature if available.
        /// </summary>
        internal static string CHKBOX_SMTPPGPSIGN {
            get {
                return ResourceManager.GetString("CHKBOX_SMTPPGPSIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string E1 {
            get {
                return ResourceManager.GetString("E1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string E2 {
            get {
                return ResourceManager.GetString("E2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string E3 {
            get {
                return ResourceManager.GetString("E3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string E4 {
            get {
                return ResourceManager.GetString("E4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string E5 {
            get {
                return ResourceManager.GetString("E5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _{0} all {1} accounts.
        /// </summary>
        internal static string GUIACCOUNT_FMT1 {
            get {
                return ResourceManager.GetString("GUIACCOUNT_FMT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set All {0}.
        /// </summary>
        internal static string GUIACCOUNT_FMT2 {
            get {
                return ResourceManager.GetString("GUIACCOUNT_FMT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to {0} all {1} account?.
        /// </summary>
        internal static string GUIACCOUNT_FMT3 {
            get {
                return ResourceManager.GetString("GUIACCOUNT_FMT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} {1} account configuration file.
        /// </summary>
        internal static string GUIACCOUNT_FMT4 {
            get {
                return ResourceManager.GetString("GUIACCOUNT_FMT4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} &apos;{1}&apos; account.
        /// </summary>
        internal static string GUIACCOUNT_FMT5 {
            get {
                return ResourceManager.GetString("GUIACCOUNT_FMT5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} &apos;{1}&apos; account?.
        /// </summary>
        internal static string GUIACCOUNT_FMT6 {
            get {
                return ResourceManager.GetString("GUIACCOUNT_FMT6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mail Accounts.
        /// </summary>
        internal static string GUIMAIL_TITLE1 {
            get {
                return ResourceManager.GetString("GUIMAIL_TITLE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Read Message.
        /// </summary>
        internal static string GUIMAILREAD_TITLE1 {
            get {
                return ResourceManager.GetString("GUIMAILREAD_TITLE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на From: address in message empty.
        /// </summary>
        internal static string GUIMAILWRITE_ERR1 {
            get {
                return ResourceManager.GetString("GUIMAILWRITE_ERR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To: address in message empty.
        /// </summary>
        internal static string GUIMAILWRITE_ERR2 {
            get {
                return ResourceManager.GetString("GUIMAILWRITE_ERR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Subject in message empty.
        /// </summary>
        internal static string GUIMAILWRITE_ERR3 {
            get {
                return ResourceManager.GetString("GUIMAILWRITE_ERR3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Body in message empty.
        /// </summary>
        internal static string GUIMAILWRITE_ERR4 {
            get {
                return ResourceManager.GetString("GUIMAILWRITE_ERR4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account not found based on sender address.
        /// </summary>
        internal static string GUIMAILWRITE_ERR5 {
            get {
                return ResourceManager.GetString("GUIMAILWRITE_ERR5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на not send.
        /// </summary>
        internal static string GUIMAILWRITE_ERR6 {
            get {
                return ResourceManager.GetString("GUIMAILWRITE_ERR6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Replay Message from: {0}.
        /// </summary>
        internal static string GUIMAILWRITE_FMT1 {
            get {
                return ResourceManager.GetString("GUIMAILWRITE_FMT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Attachments.
        /// </summary>
        internal static string GUIMAILWRITE_TEXT1 {
            get {
                return ResourceManager.GetString("GUIMAILWRITE_TEXT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Message.
        /// </summary>
        internal static string GUIMAILWRITE_TEXT2 {
            get {
                return ResourceManager.GetString("GUIMAILWRITE_TEXT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Write Message.
        /// </summary>
        internal static string GUIMAILWRITE_TITLE1 {
            get {
                return ResourceManager.GetString("GUIMAILWRITE_TITLE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} message.
        /// </summary>
        internal static string GUIMESSAGE_FMT1 {
            get {
                return ResourceManager.GetString("GUIMESSAGE_FMT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to {0} this message?.
        /// </summary>
        internal static string GUIMESSAGE_FMT2 {
            get {
                return ResourceManager.GetString("GUIMESSAGE_FMT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} - Messages : {1}.
        /// </summary>
        internal static string GUIMESSAGE_FMT3 {
            get {
                return ResourceManager.GetString("GUIMESSAGE_FMT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mail Messages.
        /// </summary>
        internal static string GUIMESSAGE_TITLE1 {
            get {
                return ResourceManager.GetString("GUIMESSAGE_TITLE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Proxy list {0} downloaded {1} hosts.
        /// </summary>
        internal static string GUIPROXY_FMT1 {
            get {
                return ResourceManager.GetString("GUIPROXY_FMT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Proxy list added {0} new hosts.
        /// </summary>
        internal static string GUIPROXY_FMT2 {
            get {
                return ResourceManager.GetString("GUIPROXY_FMT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Download all type proxy.
        /// </summary>
        internal static string GUIPROXY_MENU1 {
            get {
                return ResourceManager.GetString("GUIPROXY_MENU1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Download HTTP,HTTPS proxy.
        /// </summary>
        internal static string GUIPROXY_MENU2 {
            get {
                return ResourceManager.GetString("GUIPROXY_MENU2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Download SOCK5 proxy.
        /// </summary>
        internal static string GUIPROXY_MENU3 {
            get {
                return ResourceManager.GetString("GUIPROXY_MENU3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Proxy List.
        /// </summary>
        internal static string GUIPROXY_TITLE1 {
            get {
                return ResourceManager.GetString("GUIPROXY_TITLE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Proxy Type.
        /// </summary>
        internal static string GUIPROXY_TITLE2 {
            get {
                return ResourceManager.GetString("GUIPROXY_TITLE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Proxy Host.
        /// </summary>
        internal static string GUIPROXY_TITLE3 {
            get {
                return ResourceManager.GetString("GUIPROXY_TITLE3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check proxyes.
        /// </summary>
        internal static string GUIPROXY_TITLE4 {
            get {
                return ResourceManager.GetString("GUIPROXY_TITLE4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check proxy.
        /// </summary>
        internal static string GUIPROXY_TITLE5 {
            get {
                return ResourceManager.GetString("GUIPROXY_TITLE5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Proxy verification process is already running, please wait...
        /// </summary>
        internal static string GUIPROXY_TXT1 {
            get {
                return ResourceManager.GetString("GUIPROXY_TXT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clipboard proxy list empty.
        /// </summary>
        internal static string GUIPROXY_TXT10 {
            get {
                return ResourceManager.GetString("GUIPROXY_TXT10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на bad proxy port value.
        /// </summary>
        internal static string GUIPROXY_TXT11 {
            get {
                return ResourceManager.GetString("GUIPROXY_TXT11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete proxy host.
        /// </summary>
        internal static string GUIPROXY_TXT12 {
            get {
                return ResourceManager.GetString("GUIPROXY_TXT12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to delete proxy.
        /// </summary>
        internal static string GUIPROXY_TXT13 {
            get {
                return ResourceManager.GetString("GUIPROXY_TXT13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Proxy list empty.
        /// </summary>
        internal static string GUIPROXY_TXT14 {
            get {
                return ResourceManager.GetString("GUIPROXY_TXT14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download proxy list empty.
        /// </summary>
        internal static string GUIPROXY_TXT15 {
            get {
                return ResourceManager.GetString("GUIPROXY_TXT15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save proxy list.
        /// </summary>
        internal static string GUIPROXY_TXT16 {
            get {
                return ResourceManager.GetString("GUIPROXY_TXT16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save this proxy list to file?.
        /// </summary>
        internal static string GUIPROXY_TXT17 {
            get {
                return ResourceManager.GetString("GUIPROXY_TXT17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Proxy list saved to default file.
        /// </summary>
        internal static string GUIPROXY_TXT18 {
            get {
                return ResourceManager.GetString("GUIPROXY_TXT18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy proxy list from &apos;hidemy.name&apos; and paste it.
        /// </summary>
        internal static string GUIPROXY_TXT19 {
            get {
                return ResourceManager.GetString("GUIPROXY_TXT19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Proxy list type not selected, not verification process running...
        /// </summary>
        internal static string GUIPROXY_TXT2 {
            get {
                return ResourceManager.GetString("GUIPROXY_TXT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Proxy list is empty, not verification process running...
        /// </summary>
        internal static string GUIPROXY_TXT3 {
            get {
                return ResourceManager.GetString("GUIPROXY_TXT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Another building/verification process running...
        /// </summary>
        internal static string GUIPROXY_TXT4 {
            get {
                return ResourceManager.GetString("GUIPROXY_TXT4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Proxy verification process running...
        /// </summary>
        internal static string GUIPROXY_TXT5 {
            get {
                return ResourceManager.GetString("GUIPROXY_TXT5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Proxy host not selected, abort...
        /// </summary>
        internal static string GUIPROXY_TXT6 {
            get {
                return ResourceManager.GetString("GUIPROXY_TXT6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Begin check proxy host.
        /// </summary>
        internal static string GUIPROXY_TXT7 {
            get {
                return ResourceManager.GetString("GUIPROXY_TXT7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Proxy list clear.
        /// </summary>
        internal static string GUIPROXY_TXT8 {
            get {
                return ResourceManager.GetString("GUIPROXY_TXT8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear this proxy list.
        /// </summary>
        internal static string GUIPROXY_TXT9 {
            get {
                return ResourceManager.GetString("GUIPROXY_TXT9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SSH Accounts.
        /// </summary>
        internal static string GUISSH_TITLE1 {
            get {
                return ResourceManager.GetString("GUISSH_TITLE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на VPN Accounts.
        /// </summary>
        internal static string GUIVPN_TITLE1 {
            get {
                return ResourceManager.GetString("GUIVPN_TITLE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на wireguard VPN.
        /// </summary>
        internal static string GUIVPN_TITLE2 {
            get {
                return ResourceManager.GetString("GUIVPN_TITLE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Accounts _backup.
        /// </summary>
        internal static string MENU_ACCBACKUP {
            get {
                return ResourceManager.GetString("MENU_ACCBACKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reload _access list - IP, NET, countries.
        /// </summary>
        internal static string MENU_ACCESSRELOAD {
            get {
                return ResourceManager.GetString("MENU_ACCESSRELOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restoring copies of accounts.
        /// </summary>
        internal static string MENU_ACCLOAD {
            get {
                return ResourceManager.GetString("MENU_ACCLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Restoring accounts from a backup.
        /// </summary>
        internal static string MENU_ACCRESTORE {
            get {
                return ResourceManager.GetString("MENU_ACCRESTORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saving copies of accounts.
        /// </summary>
        internal static string MENU_ACCSAVE {
            get {
                return ResourceManager.GetString("MENU_ACCSAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Action.
        /// </summary>
        internal static string MENU_ACTION {
            get {
                return ResourceManager.GetString("MENU_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Close.
        /// </summary>
        internal static string MENU_CLOSE {
            get {
                return ResourceManager.GetString("MENU_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на D_elete.
        /// </summary>
        internal static string MENU_DELETE {
            get {
                return ResourceManager.GetString("MENU_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Brighter text in shapes.
        /// </summary>
        internal static string MENU_LIGHTTEXT {
            get {
                return ResourceManager.GetString("MENU_LIGHTTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Log.
        /// </summary>
        internal static string MENU_LOG {
            get {
                return ResourceManager.GetString("MENU_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show usage _messages cache.
        /// </summary>
        internal static string MENU_LOGCACHE {
            get {
                return ResourceManager.GetString("MENU_LOGCACHE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Clear Log.
        /// </summary>
        internal static string MENU_LOGCLEAR {
            get {
                return ResourceManager.GetString("MENU_LOGCLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Event view.
        /// </summary>
        internal static string MENU_LOGEVENT {
            get {
                return ResourceManager.GetString("MENU_LOGEVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Log view.
        /// </summary>
        internal static string MENU_LOGVIEW {
            get {
                return ResourceManager.GetString("MENU_LOGVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show messages from _VPN service.
        /// </summary>
        internal static string MENU_LOGVPN {
            get {
                return ResourceManager.GetString("MENU_LOGVPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Write log to file.
        /// </summary>
        internal static string MENU_LOGWRITE {
            get {
                return ResourceManager.GetString("MENU_LOGWRITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Mail.
        /// </summary>
        internal static string MENU_MAIL {
            get {
                return ResourceManager.GetString("MENU_MAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Mail accounts.
        /// </summary>
        internal static string MENU_MAILACCOUNT {
            get {
                return ResourceManager.GetString("MENU_MAILACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Mail Boxes.
        /// </summary>
        internal static string MENU_MAILBOX {
            get {
                return ResourceManager.GetString("MENU_MAILBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Check Mail.
        /// </summary>
        internal static string MENU_MAILCHCEK {
            get {
                return ResourceManager.GetString("MENU_MAILCHCEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _New Message.
        /// </summary>
        internal static string MENU_MAILNEW {
            get {
                return ResourceManager.GetString("MENU_MAILNEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Menu.
        /// </summary>
        internal static string MENU_MENU {
            get {
                return ResourceManager.GetString("MENU_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Proxy check started.
        /// </summary>
        internal static string MENU_PROXYCHECK {
            get {
                return ResourceManager.GetString("MENU_PROXYCHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Proxy lists.
        /// </summary>
        internal static string MENU_PROXYLIST {
            get {
                return ResourceManager.GetString("MENU_PROXYLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete non-responding _proxy servers after sending.
        /// </summary>
        internal static string MENU_PROXYREPACK {
            get {
                return ResourceManager.GetString("MENU_PROXYREPACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Proxy type selected.
        /// </summary>
        internal static string MENU_PROXYSELECT {
            get {
                return ResourceManager.GetString("MENU_PROXYSELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select _Type of proxy server.
        /// </summary>
        internal static string MENU_PROXYTYPE {
            get {
                return ResourceManager.GetString("MENU_PROXYTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Quit.
        /// </summary>
        internal static string MENU_QUIT {
            get {
                return ResourceManager.GetString("MENU_QUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Refresh menu data.
        /// </summary>
        internal static string MENU_REFRESH {
            get {
                return ResourceManager.GetString("MENU_REFRESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Reload.
        /// </summary>
        internal static string MENU_RELOAD {
            get {
                return ResourceManager.GetString("MENU_RELOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Save.
        /// </summary>
        internal static string MENU_SAVE {
            get {
                return ResourceManager.GetString("MENU_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Save all settings.
        /// </summary>
        internal static string MENU_SAVEALL {
            get {
                return ResourceManager.GetString("MENU_SAVEALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Send.
        /// </summary>
        internal static string MENU_SEND {
            get {
                return ResourceManager.GetString("MENU_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ser_vices.
        /// </summary>
        internal static string MENU_SERVICES {
            get {
                return ResourceManager.GetString("MENU_SERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Services _Settings.
        /// </summary>
        internal static string MENU_SERVSET {
            get {
                return ResourceManager.GetString("MENU_SERVSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Settings.
        /// </summary>
        internal static string MENU_SETTINGS {
            get {
                return ResourceManager.GetString("MENU_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select _SSH account.
        /// </summary>
        internal static string MENU_SSHACCOUNT {
            get {
                return ResourceManager.GetString("MENU_SSHACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SSH account selected.
        /// </summary>
        internal static string MENU_SSHSELECT {
            get {
                return ResourceManager.GetString("MENU_SSHSELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select _VPN account.
        /// </summary>
        internal static string MENU_VPNACCOUNT {
            get {
                return ResourceManager.GetString("MENU_VPNACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на VPN tunnel activation started.
        /// </summary>
        internal static string MENU_VPNBEGIN {
            get {
                return ResourceManager.GetString("MENU_VPNBEGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _VPN service can be activated.
        /// </summary>
        internal static string MENU_VPNENABLE {
            get {
                return ResourceManager.GetString("MENU_VPNENABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Always choose a random VPN account from the available ones.
        /// </summary>
        internal static string MENU_VPNRANDOM {
            get {
                return ResourceManager.GetString("MENU_VPNRANDOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на VPN tunnel ready, waiting.
        /// </summary>
        internal static string MENU_VPNREADY {
            get {
                return ResourceManager.GetString("MENU_VPNREADY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на VPN account selected.
        /// </summary>
        internal static string MENU_VPNSELECT {
            get {
                return ResourceManager.GetString("MENU_VPNSELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на VPN tunnel is working.
        /// </summary>
        internal static string MENU_VPNTUNRUN {
            get {
                return ResourceManager.GetString("MENU_VPNTUNRUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account.
        /// </summary>
        internal static string TAG_ACCOUNT {
            get {
                return ResourceManager.GetString("TAG_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Accounts.
        /// </summary>
        internal static string TAG_ACCOUNTS {
            get {
                return ResourceManager.GetString("TAG_ACCOUNTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Allowed.
        /// </summary>
        internal static string TAG_ALLOWED {
            get {
                return ResourceManager.GetString("TAG_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attach:.
        /// </summary>
        internal static string TAG_ATTACH {
            get {
                return ResourceManager.GetString("TAG_ATTACH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Access rules for IP, NET or country codes.
        /// </summary>
        internal static string TAG_BANNEDIPLIST {
            get {
                return ResourceManager.GetString("TAG_BANNEDIPLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Body.
        /// </summary>
        internal static string TAG_BODY {
            get {
                return ResourceManager.GetString("TAG_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email clients.
        /// </summary>
        internal static string TAG_CLIENTS {
            get {
                return ResourceManager.GetString("TAG_CLIENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mail check period in minutes.
        /// </summary>
        internal static string TAG_CLIENTSMAILPERIOD {
            get {
                return ResourceManager.GetString("TAG_CLIENTSMAILPERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum waiting time for mail clients.
        /// </summary>
        internal static string TAG_CLIENTSTIMEOUT {
            get {
                return ResourceManager.GetString("TAG_CLIENTSTIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date:.
        /// </summary>
        internal static string TAG_DATE {
            get {
                return ResourceManager.GetString("TAG_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        internal static string TAG_DELETE {
            get {
                return ResourceManager.GetString("TAG_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disable.
        /// </summary>
        internal static string TAG_DISABLE {
            get {
                return ResourceManager.GetString("TAG_DISABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable.
        /// </summary>
        internal static string TAG_ENABLE {
            get {
                return ResourceManager.GetString("TAG_ENABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Expire:.
        /// </summary>
        internal static string TAG_EXPIRE {
            get {
                return ResourceManager.GetString("TAG_EXPIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Access list reloaded, total {0} entries.
        /// </summary>
        internal static string TAG_FMT_ACCESSRELOAD {
            get {
                return ResourceManager.GetString("TAG_FMT_ACCESSRELOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version: {0}.
        /// </summary>
        internal static string TAG_FMT_VERSION {
            get {
                return ResourceManager.GetString("TAG_FMT_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Folder:.
        /// </summary>
        internal static string TAG_FOLDER {
            get {
                return ResourceManager.GetString("TAG_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Forbidden.
        /// </summary>
        internal static string TAG_FORBIDDEN {
            get {
                return ResourceManager.GetString("TAG_FORBIDDEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на From:.
        /// </summary>
        internal static string TAG_FROM {
            get {
                return ResourceManager.GetString("TAG_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Host:.
        /// </summary>
        internal static string TAG_HOST {
            get {
                return ResourceManager.GetString("TAG_HOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Idle:.
        /// </summary>
        internal static string TAG_IDLE {
            get {
                return ResourceManager.GetString("TAG_IDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login:.
        /// </summary>
        internal static string TAG_LOGIN {
            get {
                return ResourceManager.GetString("TAG_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Message.
        /// </summary>
        internal static string TAG_MESSAGE {
            get {
                return ResourceManager.GetString("TAG_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name:.
        /// </summary>
        internal static string TAG_NAME {
            get {
                return ResourceManager.GetString("TAG_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Network.
        /// </summary>
        internal static string TAG_NETWORK {
            get {
                return ResourceManager.GetString("TAG_NETWORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No.
        /// </summary>
        internal static string TAG_NO {
            get {
                return ResourceManager.GetString("TAG_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на don&apos;t check email.
        /// </summary>
        internal static string TAG_NOMAILCHECK {
            get {
                return ResourceManager.GetString("TAG_NOMAILCHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на the list is empty.
        /// </summary>
        internal static string TAG_NOTELEMENTS {
            get {
                return ResourceManager.GetString("TAG_NOTELEMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disabled.
        /// </summary>
        internal static string TAG_OFF {
            get {
                return ResourceManager.GetString("TAG_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ok.
        /// </summary>
        internal static string TAG_OK {
            get {
                return ResourceManager.GetString("TAG_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enabled.
        /// </summary>
        internal static string TAG_ON {
            get {
                return ResourceManager.GetString("TAG_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open/Import.
        /// </summary>
        internal static string TAG_OPEN_IMPORT {
            get {
                return ResourceManager.GetString("TAG_OPEN_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Options.
        /// </summary>
        internal static string TAG_OPTION {
            get {
                return ResourceManager.GetString("TAG_OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password:.
        /// </summary>
        internal static string TAG_PASSWORD {
            get {
                return ResourceManager.GetString("TAG_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Port:.
        /// </summary>
        internal static string TAG_PORT {
            get {
                return ResourceManager.GetString("TAG_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на proxy.
        /// </summary>
        internal static string TAG_PROXY {
            get {
                return ResourceManager.GetString("TAG_PROXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All type proxy.
        /// </summary>
        internal static string TAG_PROXYALL {
            get {
                return ResourceManager.GetString("TAG_PROXYALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Configuration saved, some options will be available after restart.
        /// </summary>
        internal static string TAG_SAVE {
            get {
                return ResourceManager.GetString("TAG_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save/Export.
        /// </summary>
        internal static string TAG_SAVE_EXPORT {
            get {
                return ResourceManager.GetString("TAG_SAVE_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Security.
        /// </summary>
        internal static string TAG_SECURITY {
            get {
                return ResourceManager.GetString("TAG_SECURITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send.
        /// </summary>
        internal static string TAG_SEND {
            get {
                return ResourceManager.GetString("TAG_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на service.
        /// </summary>
        internal static string TAG_SERVICE {
            get {
                return ResourceManager.GetString("TAG_SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Size:.
        /// </summary>
        internal static string TAG_SIZE {
            get {
                return ResourceManager.GetString("TAG_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Source.
        /// </summary>
        internal static string TAG_SOURCE {
            get {
                return ResourceManager.GetString("TAG_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of spam counter hits.
        /// </summary>
        internal static string TAG_SPAMCOUNT {
            get {
                return ResourceManager.GetString("TAG_SPAMCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Break time in minutes when a spam rule is triggered.
        /// </summary>
        internal static string TAG_SPAMTIMEOUT {
            get {
                return ResourceManager.GetString("TAG_SPAMTIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Forbidden IPs in routing.
        /// </summary>
        internal static string TAG_STOPROUTELIST {
            get {
                return ResourceManager.GetString("TAG_STOPROUTELIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Subject:.
        /// </summary>
        internal static string TAG_SUBJECT {
            get {
                return ResourceManager.GetString("TAG_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To:.
        /// </summary>
        internal static string TAG_TO {
            get {
                return ResourceManager.GetString("TAG_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type:.
        /// </summary>
        internal static string TAG_TYPE {
            get {
                return ResourceManager.GetString("TAG_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes.
        /// </summary>
        internal static string TAG_YES {
            get {
                return ResourceManager.GetString("TAG_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на abort loading.
        /// </summary>
        internal static string UTILS_ABORT {
            get {
                return ResourceManager.GetString("UTILS_ABORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Message file name is empty.
        /// </summary>
        internal static string UTILS_TXT1 {
            get {
                return ResourceManager.GetString("UTILS_TXT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Message file not found.
        /// </summary>
        internal static string UTILS_TXT2 {
            get {
                return ResourceManager.GetString("UTILS_TXT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Message file length is zero.
        /// </summary>
        internal static string UTILS_TXT3 {
            get {
                return ResourceManager.GetString("UTILS_TXT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Eroor load message.
        /// </summary>
        internal static string UTILS_TXT4 {
            get {
                return ResourceManager.GetString("UTILS_TXT4", resourceCulture);
            }
        }
    }
}
