site_name: Security Home Mail Hub

site_url: https://claudiacoord.github.io/SecurityHomeMailHub/

docs_dir: docs

nav:
    - Home: docindex.md
    - About: docabout.md

theme: bootstrap386


copyright: Copyright &copy; 2022 CC

