site_name: Security Home Mail Hub

site_url: https://claudiacoord.github.io/SecurityHomeMailHub/

docs_dir: docs

nav:
    - Home: docindex.md
    - About: docabout.md

theme: bootstrap386

  features:
    - navigation.tabs
    - navigation.sections

copyright: Copyright &copy; 2022 CC

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
