site_name: Security Home Mail Hub

site_url: https://claudiacoord.github.io/SecurityHomeMailHub/

docs_dir: docs

nav:
    - Home: index.md
    - About: about.md
<<<<<<< HEAD
=======

theme: bootstrap386

>>>>>>> a6395c318a4dd521858f82c986351d56802ee280

copyright: Copyright &copy; 2022 CC

theme: bootstrap386

plugins:
    - search
